Changeset Analysis
========================================================
Looking at OSM changeset density

```{r import_changeset_analysis, echo=FALSE, results='hide', message=FALSE}
#Load Data from Mongo?  No.
#source("/Users/jenningsanderson/Dropbox/OSM/osm-history/rcode/changesets_analysis.r")

#Philippines
#phil_cursor = custom_timeboxed_cursor(ISOdate(2013,11,08), ISOdate(2013,12,08), 'philippines.changesets')
#phil_info = buildChangeset(phil_cursor)

#Haiti
#haiti_cursor = custom_timeboxed_cursor(ISOdate(2010,01,12), ISOdate(2010,02,12), 'haiti.changesets')
#haiti_info = buildChangeset(haiti_cursor)

#Combine the DFs:
#phil_info$Country  = "Philippines"
#haiti_info$Country = "Haiti"

#dat = rbind(phil_info, haiti_info)
```

Load the Data from the disaster window CSV
```{r initial_load, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
#Load libraries
library(ggplot2)

#Load the data from csv
philippines = read.csv("/Users/jenningsanderson/Google Drive/OSM-Haiti-Philippines-SocialComputing/data/users_changesets/phil_changesets_data.csv")
haiti       = read.csv("/Users/jenningsanderson/Google Drive/OSM-Haiti-Philippines-SocialComputing/data/users_changesets/haiti_changesets_data.csv")

#Combine the two now
philippines$Country  = "Philippines"
haiti$Country        = "Haiti"

dat = rbind(philippines, haiti)
```

### Summary Statistics of the data
Philippines
```{r}
summary(philippines$node_count)
summary(philippines$area)
summary(philippines$density)
```
Haiti
```{r}
summary(haiti$node_count)
summary(haiti$area)
summary(haiti$density)
```

```{r}
log <- function(x) ifelse(x <= 0, 0, base::log(x)) #Redefine log to return 0 when undefined...
```


### Plot Node count vs area
```{r fig.width=12, another_test, message=FALSE, warning=FALSE}
ggplot(data=dat, aes(x = log(node_count), y = log(area), color=Country) ) + 
  geom_point(shape=19, alpha=1/2) +
  stat_smooth(aes(x = log(node_count), y = log(area), color=Country), method = "lm", formula = y ~ x, size = 1)
```

### Histogram of densities
```{r}
ggplot(dat, aes(log(density), fill = Country)) + geom_histogram(alpha = 0.5, binwidth=.1, position = 'identity')
```

```{r echo=FALSE} 
#[sample(nrow(dat),10000),]
```

### What about just density overtime?
```{r fig.width=12, count_v_area, message=FALSE, warning=FALSE}
ggplot(data=dat[dat$area > 1, ], aes(x = log(area), y = log(density), color=Country) ) + 
  geom_point(shape=19, alpha=1/2) +
  stat_smooth(method = "lm", size = 1)
```


### Plotting Node Density against user joining date
```{r fig.width=12, density, message=FALSE, warning=FALSE}
#Plot them against eachother:
ggplot(aes(x = userjoin, y = log(node_density), color=Country), data=dat) +  geom_point(shape=19,alpha=1/2)
```

